### ISSUE TITLE
Starting or Ending Combat Stops Currently Playing Audio

### ISSUE THREAD

**Issue by KellethDregar** [veevelder/quick-combat#16] opened 2021-12-30 09:50 UTC
So I updated to the latest version of quick-combat today and have noticed that whenever we start or end combat it automatically kills any audio currently playing (stops and completely removes it from currently playing.) 

Currently running Foundry 0.8.9 on Forge and on Quick-combat version 0.2.5.

Here is the error caught in the console:
![image](https://user-images.githubusercontent.com/79947702/147740682-2254f937-defa-4e03-8f41-54935bb82ecd.png)

**Comment by veevelder** [comment] 2022-01-05 22:25
Thanks for the report, can you turn on the debug output on the console for me so I can see the output? Also I think I know the reason, if you could try and resave the quick combat settings I changed how the playlists are saved and im wondering if thats the cause.

**Comment by veevelder** [comment] 2022-01-05 23:00
I managed to recreate the issue, and it was what I suspected, I will make a note of it on the readme let me know if the fix works for you.

**Comment by KellethDregar** [comment] 2022-01-07 00:11
It seems to still be happening, it is currently happening when combat is ended the music playlist will be stopped and removed.

Here are the current settings I have:
![image](https://user-images.githubusercontent.com/79947702/148470204-cbee02c0-581b-49a2-9b13-112ec9071488.png)

**Comment by KellethDregar** [comment] 2022-01-07 00:34
Ah nevermind still seems to be happening on start and stop

![image](https://user-images.githubusercontent.com/79947702/148472018-0023cbdd-53bf-449a-96ed-a0313119250a.png)

**Comment by KellethDregar** [comment] 2022-01-07 00:53
Seems like sometimes it stops it at combat start but it always will stop it at combat end.

**Comment by veevelder** [comment] 2022-01-07 16:43
first thing I notice is that you dont have any playlist set for combat, fanfare or boss. At a minimum you need to have at least the Combat Playlist set to something. Also currently this version only works when using the keybinds and not the start/end combat buttons on the combat tracker, so make sure you are using that. This was fixed in the newer versions of Quick Combat but that uses the newest version 9 of FoundryVTT

**Comment by veevelder** [comment] 2022-01-17 14:09
just wanted to see if you are still having any problems

**Comment by veevelder** [comment] 2022-01-24 17:48
closing due to no response

**Closed by veevelder** 2022-01-24 17:48 UTC
